<?php

echo "<li nodetreeid=\"{$content['node']}\" class=\"mjs-nestedSortable-no-nesting mjs-nestedSortable-leaf\"><div class=\"ui-sortable-handle\"><div class=\"node-heading\">";

echo '<div class="controls">';
$this->printField($content, 'reference', '<span title="Click to edit node" class="fa fa-pencil" onclick="window.open(\'' . BonsaiEdit\Module\Registry::get('nodeEditPath') . '%s\');"></span>');
    
echo BonsaiEdit\Module\Registry::get('usePreview') ? $this->renderField($content, 'node', '<span title="Click to preview node" class="preview fa fa-eye" onclick="window.open(\'' . BonsaiEdit\Module\Registry::get('previewPath') . '%s\');"></span>') : '';

$this->printField($content, 'contentref', '<span title="Click to edit content" class="fa fa-pencil-square-o" onclick="window.open(\'' . BonsaiEdit\Module\Registry::get('contentEditPath') . '%s\');"></span>');
echo '<span title="Click to remove node" class="destroy fa fa-remove"></span>';
echo '</div>';

echo $content['reference'];
echo "</div><div>{$content['content']}</div></div></li>";
